portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import send_email

app_name = "portfolio"

urlpatterns = [
    path("", views.home, name="home"),
    path("send_message/", send_email, name="send_message"),
    path("post/<int:id>/", views.post_detail, name="post_detail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

protfolio_final_base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="posts/")
    # blog_body = models.TextField(max_length=5000, blank=False, null=False, default='')
    blog_body = RichTextField(max_length=5000, blank=False, null=False, default="")
    blog_list_description = models.TextField(
        max_length=1000, blank=False, null=False, default=""
    )
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Experience(models.Model):
    job_title = models.CharField(max_length=100, blank=True, null=True, default="")
    company = models.CharField(max_length=100, blank=True, null=True, default="")
    role_description = models.TextField(max_length=1000)
    time_working_for_company = models.CharField(
        max_length=100, blank=True, null=True, default=""
    )

    def __str__(self):
        return f"{self.job_title} at {self.company}"


class Skills(models.Model):
    skill = models.CharField(max_length=50, blank=True, null=True, default="")
    skill_percentage = models.IntegerField()

    class Meta:
        verbose_name_plural = "Skills"

    def __str__(self):
        return f"{self.skill} {self.skill_percentage}%"


class Certificates(models.Model):
    certificate_title = models.CharField(
        max_length=250, blank=True, null=True, default=""
    )
    certificate_aquired_through = models.CharField(
        max_length=100, blank=True, null=True, default=""
    )
    certificate_description = models.TextField(
        max_length=1000, blank=True, null=True, default=""
    )
    certificate_completion_date = models.CharField(
        max_length=50, blank=True, null=True, default=""
    )

    class Meta:
        verbose_name_plural = "Certificates"

    def __str__(self):
        return f"{self.certificate_title} from {self.certificate_aquired_through}"


class NavDataTarget(models.Model):
    nav_data_target = models.CharField(max_length=50, blank=True, null=True, default="")

    def __str__(self):
        return self.nav_data_target


class MyWork(models.Model):
    data_target = models.ForeignKey(
        NavDataTarget, on_delete=models.CASCADE, blank=False, null=False
    )
    image = models.ImageField(blank=True, null=True)
    project_title = models.CharField(max_length=50, blank=True, null=True, default="")
    project_link = models.CharField(max_length=100, blank=True, null=True, default="")
    project_source_code_link = models.CharField(
        max_length=100, blank=True, null=True, default=""
    )

    class Meta:
        verbose_name_plural = "My Work"

    def __str__(self):
        return f"{self.project_title}"


class AboutMe(models.Model):
    about_me_blurb = RichTextField(max_length=5000, blank=True, null=True, default="")
    download_cv = models.FileField(blank=True, null=True, upload_to='media/CV')

    class Meta:
        verbose_name_plural = "About Me"


class Message(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False, default="")
    email = models.EmailField(max_length=200, blank=True, null=True, default="")
    subject = models.CharField(max_length=200, blank=False, null=False, default="")
    content = models.TextField(max_length=5000, blank=True, null=True, default="")

    def __str__(self):
        return f"{self.name} is asking about {self.subject}"

portfolio/views.py
import json
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Post, Experience, Skills, Certificates, Message, MyWork, AboutMe, NavDataTarget


def home(request):
    context = {
        "posts": Post.objects.all().order_by("-date"),
        "experiences": Experience.objects.all(),
        "skills": Skills.objects.all(),
        "certificates": Certificates.objects.all().order_by(
            "-certificate_completion_date"
        ),
        "myworks": MyWork.objects.all(),
        "navDataTargets": NavDataTarget.objects.all(),
        "aboutme": AboutMe.objects.all(),
    }
    return render(request, "index.html", context)


def post_detail(request, id):
    post = Post.objects.get(id=id)
    next_post = Post.objects.filter(id__gt=post.id).order_by("id").first()
    previous_post = Post.objects.filter(id__lt=post.id).order_by("-id").first()
    context = {
        "post": post,
        "next_post": next_post,
        "previous_post": previous_post,
    }
    return render(request, "blog-single-1.html", context)


@csrf_exempt
def send_email(request):
    if request.method == "POST":
        data = json.loads(request.body)
        name = data.get("userName")
        email = data.get("userEmail")
        subject = data.get("subject")
        content = data.get("content")

        Message.objects.create(name=name, email=email, subject=subject, content=content)

        return JsonResponse({"message": "Message saved successfully."})
    else:
        return JsonResponse({"error": "Invalid request."}, status=400)

templates/about.html
{% load static %}
<section class="page" id="about">
    <header>
        <span class="title">About</span>
        <span class="title-number">01</span>
    </header>

    <div class="content grid">
        <div class="page-header c12">
            <h1 data-value="About me">About Me</h1>
            <hr>
        </div>
        <div class="row">
            <div class="c6">
                <div class="about-slider">
                    <img src="{% static 'img/Delroy_Brown.png' %}" alt="slide one">
                    <img src="{% static 'img/720x720.jpg' %}" alt="slide two">
                    <img src="{% static 'img/720x720.jpg' %}" alt="slide three">
                </div>
            </div>
            <div class="c6">

                <div class="col-top">
                    <h2>Delroy Brown</h2>
                    <h5>Freelancer Extraordinaire</h5>
                    <hr>
                    <p>
                        {% for about in aboutme %}

                        {{about.about_me_blurb|safe }}
                        <span class="spacer"></span>
                        <a href="{% static 'CV/DBrown_CV2.pdf' %}" class="button" download>Download CV <i
                            class="lni lni-download"></i></a>
                            {% endfor %}
                    </p>
                </div>

                <div class="col-bottom">
                    <hr>
                    <div class="about-slider-controls">
                        <span class="prev-slide"><i class="lni lni-chevron-left"></i></span>
                        <span class="next-slide"><i class="lni lni-chevron-right"></i></span>
                    </div>
                    <p class="slide-number">Image <span class="current-slide">One</span> Of Three</p>
                </div>

            </div>
        </div><!--END ROW-->


        <div class="spacer"></div>
        <div class="row">

            <div class="c4">
                <ul class="tabs-nav">
                    <li><a href="#" id="tab1"><span>Programming Skills</span></a><span class="tab-background"></span>
                    </li>
                    <li><a href="#" id="tab2"><span>Certificates</span></a><span class="tab-background"></span></li>
                    <li><a href="#" id="tab3"><span>Experience</span></a><span class="tab-background"></span></li>
                </ul>
            </div>
            <div class="c8">

                <!-- SKILLS -->
                <div class="tabs-container" id="tab1-content">
                    {% for skill in skills %}

                    <p class="skill-title">{{skill.skill}} <span>{{ skill.skill_percentage }}%</span></p>
                    <div class="skill-bar-wrapper">
                        <div class="skill-bar enabled"><span style="width:{{skill.skill_percentage}}%"></span></div>
                    </div>
                    {% endfor %}
                </div>

                <!-- CERTIFICATES -->
                <div class="tabs-container" id="tab2-content">
                    {% for certificate in certificates %}
                    <div class="row">
                        <div class="c8">
                            <h4>{{ certificate.certificate_title }}</h4>
                            <h6>{{ certificate.certificate_aquired_through }}</h6>
                            <p>{{ certificate.certificate_description }}</p>
                        </div>
                        <div class="c4">
                            <h4 class="align-right">{{ certificate.certificate_completion_date }}</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="c12">
                            <hr>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <!-- EXPERIENCE -->
                <div class="tabs-container" id="tab3-content">
                    {% for experience in experiences %}
                    <div class="row">
                        <div class="c8">

                            <h4>{{ experience.job_title }}</h4>
                            <h6>{{ experience.company }}</h6>
                            <p>{{ experience.role_description }}
                            </p>
                        </div>
                        <div class="c4">
                            <h4 class="align-right">{{ experience.time_working_for_company }}</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="c12">
                            <hr>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div><!--END ROW-->

        <!-- <div class="row">
            <div class="c12">
                <hr>
                <h5>Testomonials</h5>
            </div>
        </div> -->
        <!--END ROW-->
        <!-- TESTIMONIALS -->
        <!-- <div class="row">
            <div class="c9">

                <div class="testomonial-slider">
                    <div class="testomonial">
                        <blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consectetur
                                venenatis euismod. Cras ac velit accumsan, convallis nunc nec, volutpat sapien. Ut
                                placerat, arcu sit amet euismod elementum, orci lorem consequat nulla, in feugiat
                                turpis ligula sit amet est.</p>
                            <cite>Bob Fox. / CEO at Stock Industries</cite>
                        </blockquote>
                    </div>
                    <div class="testomonial">
                        <blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consectetur
                                venenatis euismod. Cras ac velit accumsan, convallis nunc nec, volutpat sapien. Ut
                                placerat, arcu sit amet euismod elementum, orci lorem consequat nulla, in feugiat
                                turpis ligula sit amet est.</p>
                            <cite>Bob Fox. / CEO at Stock Industries</cite>
                        </blockquote>
                    </div>
                    <div class="testomonial">
                        <blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consectetur
                                venenatis euismod. Cras ac velit accumsan, convallis nunc nec, volutpat sapien. Ut
                                placerat, arcu sit amet euismod elementum, orci lorem consequat nulla, in feugiat
                                turpis ligula sit amet est.</p>
                            <cite>Bob Fox. / CEO at Stock Industries</cite>
                        </blockquote>
                    </div>
                </div>
            </div>
            <div class="c3">
                <div class="testomonial-slider-controls">
                    <span class="prev-slide"><i class="lni lni-chevron-left"></i></span>
                    <span class="next-slide"><i class="lni lni-chevron-right"></i></span>
                </div>
            </div>

        </div> -->
        <!--END ROW-->

        <!-- CLIENTS -->
        <!-- <div class="row">
            <div class="c12">
                <hr>
                <h5>Clients</h5>
            </div>
        </div> -->
        <!--END ROW-->
        <!-- <div class="row">
            <div class="c12 end">
                <div class="slider client-slider">
                    <div><img src="{% static 'img/400x400.jpg' %}" alt="logo"></div>
                    <div><img src="{% static 'img/400x400.jpg' %}" alt="logo"></div>
                    <div><img src="{% static 'img/400x400.jpg' %}" alt="logo"></div>
                    <div><img src="{% static 'img/400x400.jpg' %}" alt="logo"></div>
                    <div><img src="{% static 'img/400x400.jpg' %}" alt="logo"></div>
                    <div><img src="{% static 'img/400x400.jpg' %}" alt="logo"></div>
                    <div><img src="{% static 'img/400x400.jpg' %}" alt="logo"></div>
                    <div><img src="{% static 'img/400x400.jpg' %}" alt="logo"></div>
                </div>
            </div>
        </div> -->
        <!--END ROW-->
        {% include "includes/footer.html" %}
    </div><!--END CONTENT-->
</section>

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Delroy J. Brown</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preload"
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Open+Sans&family=Space+Mono:wght@400;700"
        as="font" type="font/woff" crossorigin>
        <link rel="preload" href="{% static 'img/background.jpg' %}" as="image">
        <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Open+Sans&family=Space+Mono:wght@400;700">
        
        <link rel="stylesheet" href="{% static 'css/lineicons.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/imagehover.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/leaflet.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/prism.css' %}">
        <link rel="stylesheet" href="{% static 'css/codesnippets.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css">


</head>

<body>
    {% block content %}
    
    
    {% endblock content %}

    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/leaflet.js' %}"></script>
    <script src="{% static 'js/musicPlayer.js' %}"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            document.querySelectorAll('pre code').forEach((block) => {
                hljs.highlightBlock(block);
            });
        });
    </script> -->


   
</body>

</html>

templates/blog-single-1.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css">


<main>
  <section class="page">
    <header>
      <span class="title">Blog</span>
    </header>
    <div class="content grid">
      <div class="page-header c12">
        <h1 class="beta">{{ post.title }}</h1>
        <!-- <span class="toggle-sidebar"><i></i></span> -->
      </div>

      <nav id="nav-above">
        <div id="crumbs">
          <span><a class="blog-home" href="#">Home</a></span>
          <span> » </span>
          <span>{{post.title}}</span>
        </div>
        {% if next_post %}
        <div class="nav-next">
          <a href="{% url 'portfolio:post_detail' id=next_post.id %}" rel="next"
            >Next Post</a
          >
        </div>
        {% endif %} {% if previous_post %}
        <div class="nav-previous">
          <a
            href="{% url 'portfolio:post_detail' id=previous_post.id %}"
            rel="prev"
            >Previous Post</a
          >
        </div>
        {% endif %}
      </nav>

      <div class="blog-recent-post-item row">
        <div class="c12 end">
          <p><img class="feature" src="{{ post.image.url }}" /></p>
          <p class="gamma entry-title" style="font-size: 20px">
            {{ post.title }}
          </p>
          <div>{{ post.blog_body|safe }}</div>

          <div class="entry-meta">
            <span>By <a href="#">{{ post.created_by }}</a></span>
            <span><time class="entry-date">{{ post.date }}</time></span>

            <!-- <a href="#">3 Comments</a> -->
          </div>
        </div>
      </div>

      <!-- COMMENTS IN SEPARATE FILE -->
      <div id="sidebar">
        <aside>
          <form
            role="search"
            id="searchform"
            class="searchform"
            onsubmit="return false;"
          >
            {% csrf_token %}
            <div>
              <input type="text" name="s" id="s" placeholder="Search for:" />
              <input type="submit" id="searchsubmit" />
              <i class="lni lni-search-alt"></i>
            </div>
          </form>
        </aside>
        <aside>
          <h6 class="widget-title">Recent Posts</h6>
          <ul>
            <li><a href="#">Lorem ipsum dolor sit</a></li>
            <li><a href="#">On ultricies nisi voluptatem</a></li>
            <li><a href="#">Consectetur adipiscing elit</a></li>
            <li><a href="#">Aenean et volutpat felis</a></li>
            <li><a href="#">Donec vestibulum neque quis</a></li>
          </ul>
        </aside>
        <aside>
          <h6 class="widget-title">Text Widget</h6>
          <p class="textwidget">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Pellentesque bibendum diam justo, eget consequat mauris blandit
            vitae.
          </p>
        </aside>
        <aside>
          <h6 class="widget-title">Categories</h6>
          <ul>
            <li><a href="#">Design</a></li>
            <li><a href="#">Image</a></li>
            <li><a href="#">Photography</a></li>
            <li><a href="#">Blog</a></li>
          </ul>
        </aside>
        <aside>
          <h6 class="widget-title">Tags</h6>
          <div class="tagcloud">
            <a href="#" style="font-size: 15.777777777778pt">Image</a>
            <a href="#" style="font-size: 8pt">Design</a>
            <a href="#" style="font-size: 22pt">Photography</a>
            <a href="#" style="font-size: 15.777777777778pt">Blog</a>
          </div>
        </aside>
      </div>
      {% include "includes/footer.html" %}
    </div>
  </section>
  <!--END BLOG-->
</main>

{% endblock content %}

templates/blog.html
{% load static %}

<section class="page" id="blog">
  <header>
    <span class="title">Blog</span>
    <span class="title-number">03</span>
  </header>
  <div class="content grid">
    <div class="page-header c12">
      <h1 data-value="Latest News">Latest News</h1>
      <!-- <span class="toggle-sidebar"><i></i></span> -->
      <hr />
    </div>

    <!-- BLOG POSTS -->
    {% for post in posts %}
    <div class="blog-recent-post-item row">
      <div class="c12 end">
        <a
          class="recent-post-img"
          href="{% url 'portfolio:post_detail' id=post.id %}"
          rel=""
        >
          <img src="{{ post.image.url }}" alt="{{ post.title }}" />
          <span class="date"
            ><span class="day">{{ post.date|date:"d"}}</span> {{
            post.date|date:"F Y"}}</span
          >
        </a>
        <h2 class="gamma entry-title">
          <a href="{% url 'portfolio:post_detail' id=post.id %}" rel=""
            >{{ post.title }}</a
          >
        </h2>
        <p>{{ post.blog_list_description }}</p>
        <div class="entry-meta">
          <span>By {{ post.created_by }}</span>
          <span
            ><time class="entry-date" datetime="2013-11-17T09:00:33+00:00"
              >{{ post.date|date:"D d F Y" }}
            </time></span
          >
          <!-- <span class="cat-links">In
                        <a class="dummy" href="#" rel="category tag">Image</a>,
                        <a class="dummy" href="#" rel="category tag">Photography</a>,
                        <a class="dummy" href="#" rel="category tag">Blog</a>
                    </span>
                    <a class="dummy" href="#">25 Comments</a> -->
          <a
            class="readmore"
            href="{% url 'portfolio:post_detail' id=post.id %}"
            >Read more</a
          >
        </div>
      </div>
    </div>
    {% endfor %}

    <!-- <div class="blog-recent-post-item row">
            <div class="c12 end">
                <a class="recent-post-img" href="blog-single-2.html" rel="">
                    <img src="{% static 'img/1900x650.jpg' %}" alt="Blog">
                    <span class="date"><span class="day">21</span> Feb 2023</span>
                </a>
                <h2 class="gamma entry-title"><a href="blog-single-2.html" rel="">Explicabo Nemo</a></h2>
                <p>Bllo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo nemo enim ipsam
                    voluptatem.voluptatem, illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                    explicabo nemo enim ipsam voluptatem. on ultricies nisi voluptatem, illo inventore veritatis et
                    quasi architecto beatae vitae dicta sunt explicabo nemo enim ipsam voluptatem.voluptatem, illo
                    inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo nemo enim ipsam
                    voluptatem. Illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo</p>
                <div class="entry-meta">
                    <span>By <a class="dummy" href="#">WebDingo</a></span>
                    <span><time class="entry-date" datetime="2013-11-17T09:00:33+00:00">February 21,
                            2023</time></span>
                    <span class="cat-links">In
                        <a class="dummy" href="#" rel="category tag">Image</a>,
                        <a class="dummy" href="#" rel="category tag">Photography</a>,
                        <a class="dummy" href="#" rel="category tag">Blog</a>
                    </span>
                    <a class="dummy" href="#">25 Comments</a>
                    <a class="readmore" href="blog-single-2.html">Read more</a>
                </div>
            </div>
        </div> -->
    <!-- <div class="blog-recent-post-item row">
            <div class="c12 end">
                <a class="recent-post-img" href="blog-single-3.html" rel="">
                    <img src="{% static 'img/1900x650.jpg' %}" alt="Blog">
                    <span class="date"><span class="day">19</span> Feb 2023</span>
                </a>
                <h2 class="gamma entry-title"><a href="blog-single-3.html" rel="">Illo inventore</a></h2>
                <p>Bllo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo nemo enim ipsam
                    voluptatem.voluptatem, illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                    explicabo nemo enim ipsam voluptatem. on ultricies nisi voluptatem, illo inventore veritatis et
                    quasi architecto beatae vitae dicta sunt explicabo nemo enim ipsam voluptatem.voluptatem, illo
                    inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo nemo enim ipsam
                    voluptatem. Illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo</p>
                <div class="entry-meta">
                    <span>By <a class="dummy" href="#">WebDingo</a></span>
                    <span><time class="entry-date" datetime="2013-11-17T09:00:33+00:00">February 19,
                            2023</time></span>
                    <span class="cat-links">In
                        <a class="dummy" href="#" rel="category tag">Image</a>,
                        <a class="dummy" href="#" rel="category tag">Photography</a>,
                        <a class="dummy" href="#" rel="category tag">Blog</a>
                    </span>
                    <a class="dummy" href="#">25 Comments</a>
                    <a class="readmore" href="blog-single-3.html">Read more</a>
                </div>
            </div>
        </div> -->

    <!-- <div id="sidebar">
            <aside>

                <form role="search" id="searchform" class="searchform" onsubmit="return false;">
                    <div>
                        <input type="text" name="s" id="s" placeholder="Search for:">
                        <input type="submit" id="searchsubmit">
                        <i class="lni lni-search-alt"></i>
                    </div>
                </form>
            </aside>
            <aside>
                <h6 class="widget-title">Recent Posts</h6>
                <ul>
                    <li><a href="#">Lorem ipsum dolor sit</a></li>
                    <li><a href="#">On ultricies nisi voluptatem</a></li>
                    <li><a href="#">Consectetur adipiscing elit</a></li>
                    <li><a href="#">Aenean et volutpat felis</a></li>
                    <li><a href="#">Donec vestibulum neque quis</a></li>
                </ul>
            </aside>
            <aside>
                <h6 class="widget-title">Text Widget</h6>
                <p class="textwidget">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum
                    diam justo, eget consequat mauris blandit vitae.</p>
            </aside>
            <aside>
                <h6 class="widget-title">Categories</h6>
                <ul>
                    <li><a href="#">Design</a></li>
                    <li><a href="#">Image</a></li>
                    <li><a href="#">Photography</a></li>
                    <li><a href="#">Blog</a></li>
                </ul>
            </aside>
            <aside>
                <h6 class="widget-title">Tags</h6>
                <div class="tagcloud">
                    <a href="#" style="font-size: 15.777777777778pt;">Image</a>
                    <a href="#" style="font-size: 8pt;">Design</a>
                    <a href="#" style="font-size: 22pt;">Photography</a>
                    <a href="#" style="font-size: 15.777777777778pt;">Blog</a>
                </div>
            </aside>
        </div> -->
    {% include "includes/footer.html" %}
  </div>
  <!--END CONTENT-->
</section>

templates/includes/footer.html
<footer>
    <div class="row">
        <div class="c12 end">
            <div class="footer-inner">
                <p class="copyright">© 2023 Delroy J. Brown. All Rights Reserved.
                </p>
                <ul class="social-footer">
                    <li><a target="_blank" href="https://www.instagram.com/delroyjbrown"><i
                                class="lni lni-instagram"></i></a></li>
                    <li><a target="_blank" href="https://www.linkedin.com/in/delroy-brown-b83045226/"><i
                                class="lni lni-linkedin"></i></a></li>
                    {% comment %} <li><a target="_blank" href="https://www.facebook.com/"><i
                                class="lni lni-facebook"></i></a></li>
                    <li><a target="_blank" href="https://www.dribbble.com/"><i
                                class="lni lni-dribbble"></i></a></li> {% endcomment %}
                </ul>
            </div>
        </div>
    </div>
</footer>